"""Run labels

Revision ID: dfacdd2bd41e
Revises: 82ca43f05c10
Create Date: 2017-11-13 15:35:45.273283

"""

# revision identifiers, used by Alembic.
revision = 'dfacdd2bd41e'
down_revision = '82ca43f05c10'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels'))
    )
    op.create_table('run_labels',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], [u'labels.id'], name=op.f('fk_run_labels_label_id_labels'), ondelete=u'CASCADE', initially=u'DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['run_id'], [u'runs.id'], name=op.f('fk_run_labels_run_id_runs'), ondelete=u'CASCADE', initially=u'DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('run_id', 'label_id', name=op.f('pk_run_labels'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
