name: codechecker-linters

# Triggers the workflow on push or pull request events.
on: [push, pull_request]

jobs:
  # Note: UI related linter tests will run in the gui job.
  lint:
    name: Linters (pylint, pycodestyle)

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          pip install $(grep -iE "pylint|pycodestyle" analyzer/requirements_py/dev/requirements.txt)
      - name: Run tests
        run: make pylint pycodestyle
